---
- name: Install PostgreSQL
  yum:
    name: postgresql-server
    state: present

- name: Initialize PostgreSQL database
  command: /usr/bin/postgresql-setup initdb
  args:
    creates: /var/lib/pgsql/data/PG_VERSION

- name: Start PostgreSQL service
  systemd:
    name: postgresql
    state: started
    enabled: true

- name: Create PostgreSQL database
  postgresql_db:
    name: "{{ db_name }}"
    login_user: postgres

- name: Create PostgreSQL user
  postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    login_user: postgres
    state: present
