---
- name: Install dependencies
  yum:
    name:
      - build-base
      - libxml2-devel
    state: present

- name: Install Ruby using RVM
  shell: |
    curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -
    curl -sSL https://rvm.io/pkuczynski.asc | gpg2 --import -
    curl -sSL https://get.rvm.io | bash -s stable
    source /etc/profile.d/rvm.sh
    rvm install 2.5.1
    rvm use 2.5.1 --default
    gem install bundler
  args:
    creates: /usr/local/rvm/rubies/ruby-2.5.1

- name: Clone application repository
  git:
    repo: 'https://gitlab.slurm.io/edu/xpaste_practicum'
    dest: /opt/xpaste
    version: master

- name: Install application dependencies
  command: bundle install --clean --no-cache --without development
  args:
    chdir: /opt/xpaste

- name: Migrate the database
  command: bundle exec rake db:migrate RAILS_ENV=production
  args:
    chdir: /opt/xpaste

- name: Copy systemd service file
  template:
    src: xpaste.service.j2
    dest: /etc/systemd/system/xpaste.service

- name: Start xpaste service
  systemd:
    name: xpaste
    state: started
    enabled: true
